CapaPresentacion/Controllers/CompaniaController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    [Authorize]
    public class CompaniaController : Controller
    {
        // GET: Compania
        public ActionResult Sucursales()
        {
            return View();
        }
        public ActionResult ComprobantesFiscales()
        {
            return View();
        }

        #region SUCURSALES
        [HttpGet]
        public JsonResult ListarSucursales()
        {
            List<Compania> oLista = new List<Compania>();

            oLista = new CN_Sucursales().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarSucursales(Compania obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.Id_Compania == 0)
            {
                resultado = new CN_Sucursales().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_Sucursales().Modificar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarSucursal(int Id_Compania)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Sucursales().Eliminar(Id_Compania, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region TIPOS NCF
        [HttpGet]
        public JsonResult ListarTiposNcf()
        {
            List<TiposNcf> oLista = new List<TiposNcf>();

            oLista = new CN_TiposNcf().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarTiposNcf(TiposNcf obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.Tipo_Ncf == "")
            {
                resultado = new CN_TiposNcf().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_TiposNcf().Modificar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarTiposNcf(string Tipo_Ncf)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_TiposNcf().Eliminar(Tipo_Ncf, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

CapaPresentacion/Controllers/ProductosController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacion.Controllers
{
    [Authorize]
    public class ProductosController : Controller
    {
        // GET: Productos
        public ActionResult Productos()
        {
            return View();
        }
        public ActionResult Marcas()
        {
            return View();
        }
        public ActionResult Presentaciones()
        {
            return View();
        }
        public ActionResult Sustancias()
        {
            return View();
        }
        public ActionResult Existencias()
        {
            return View();
        }
        public ActionResult CambiosDePrecios()
        {
            return View();
        }
        public ActionResult CambiosMasivos()
        {
            return View();
        }

        #region PRODUCTOS
        [HttpGet]
        public JsonResult ListarProducto()
        {
            List<Productos> oLista = new List<Productos>();

            oLista = new CN_Productos().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarProducto(Productos obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.Id_Producto == 0)
            {
                resultado = new CN_Productos().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_Productos().Modificar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarProducto(int Id_Producto)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Productos().Eliminar(Id_Producto, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region MARCAS
        [HttpGet]
        public JsonResult ListarMarca()
        {
            List<MarcasProductos> oLista = new List<MarcasProductos>();

            oLista = new CN_MarcasProductos().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarMarca(MarcasProductos obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.Id_Marca_Producto == 0)
            {
                resultado = new CN_MarcasProductos().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_MarcasProductos().Modificar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarMarca(int Id_Marca_Producto)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_MarcasProductos().Eliminar(Id_Marca_Producto, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region PRESENTACIONES
        [HttpGet]
        public JsonResult ListarPresentacion()
        {
            List<Presentaciones> oLista = new List<Presentaciones>();

            oLista = new CN_Presentaciones().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarPresentacion(Presentaciones obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.Id_Presentacion == 0)
            {
                resultado = new CN_Presentaciones().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_Presentaciones().Modificar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarPresentacion(int Id_Presentacion)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Presentaciones().Eliminar(Id_Presentacion, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region SUSTANCIAS
        [HttpGet]
        public JsonResult ListarSustancia()
        {
            List<Sustancias> oLista = new List<Sustancias>();

            oLista = new CN_Sustancias().Listar();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GuardarSustancia(Sustancias obj)
        {
            object resultado;
            string mensaje = string.Empty;

            if (obj.Id_Sustancia == 0)
            {
                resultado = new CN_Sustancias().Registrar(obj, out mensaje);
            }
            else
            {
                resultado = new CN_Sustancias().Modificar(obj, out mensaje);
            }
            return Json(new { resultado = resultado, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult EliminarSustancia(int Id_Sustancia)
        {
            bool respuesta = false;
            string mensaje = string.Empty;

            respuesta = new CN_Sustancias().Eliminar(Id_Sustancia, out mensaje);

            return Json(new { resultado = respuesta, mensaje = mensaje }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region GRUPOS
        [HttpGet]
        public JsonResult ListarGrupo()
        {
            List<Grupos> oLista = new List<Grupos>();

            oLista = new CN_Recursos().ListarGrupo();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region SUBGRUPOS
        [HttpGet]
        public JsonResult ListarSubgrupo()
        {
            List<Subgrupos> oLista = new List<Subgrupos>();

            oLista = new CN_Recursos().ListarSubgrupo();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region TIPO PRODUCTO
        [HttpGet]
        public JsonResult ListarTipoProducto()
        {
            List<TiposDeProductos> oLista = new List<TiposDeProductos>();

            oLista = new CN_Recursos().ListarTipoProducto();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region TIPO IMPUESTO
        [HttpGet]
        public JsonResult ListarTipoImpuesto()
        {
            List<TiposDeImpuestos> oLista = new List<TiposDeImpuestos>();

            oLista = new CN_Recursos().ListarTipoImpuesto();

            return Json(new { data = oLista }, JsonRequestBehavior.AllowGet);
        }
        #endregion


    }
}

CapaPresentacion/Views/Productos/CambiosDePrecios.cshtml
@{
    ViewBag.Title = "CambiosDePrecios";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CambiosDePrecios</h2>

CapaPresentacion/Views/Productos/CambiosMasivos.cshtml
@{
    ViewBag.Title = "CambiosMasivos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CambiosMasivos</h2>

CapaPresentacion/Views/Productos/Existencias.cshtml
@{
    ViewBag.Title = "Existencias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Existencias</h2>

CapaPresentacion/Views/Productos/Marcas.cshtml
@{
    ViewBag.Title = "Marcas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Escritorio</a></li>
    <li class="breadcrumb-item active">Marcas</li>
</ol>

<div class="card">
    <div class="card-header">

        <i class="fas fa-trademark me-1"></i> Marcas
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Registrar</button>
            </div>
        </div>

        <hr />

        <table id="tabla" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>Compania</th>
                    <th>Descripcion</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Marca</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body g-2">

                <input id="txtid" type="hidden" value="0" />

                <div class="col-sm-6">
                    <label class="form-label">Compañía</label>
                    <select id="cbocompania" class="form-select">
                    </select>
                </div>
                <div class="row g-1">
                    <div class="col-sm-6">
                        <label for="txtdescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtdescripcion">
                    </div>
                    <div class="col-sm-6">
                        <label for="cboestado" class="form-label">Estado</label>
                        <select id="cboestado" class="form-select">
                            <option value="1">Activo</option>
                            <option value="0">No activo</option>
                        </select>
                    </div>
                </div>

                <!--Mensaje de alerta-->
                <div class="row mt-2">
                    <div class="col-12">

                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarMarca", "Productos")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                {
                    "data": "oId_Compania", "render": function (data) {
                        return data.Id_Compania
                    }
                },
                { "data": "Descripcion_Marca" },
                {
                    "data": "Estado_Marca", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-success">Activo</span>'
                        } else {
                            return '<span class="badge bg-danger">No activo</span>'
                        }
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }
            ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            }

        });

        jQuery.ajax({
            url: '@Url.Action("ListarSucursales", "Compania")',
            type: "GET",
            data: null,
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (data) {

                $("<option>").attr({ "value": "0","disabled":"true" }).text("Seleccionar").appendTo("#cbocompania");
                $.each(data.data, function (index, item) {
                    $("<option>").attr({ "value": item.Id_Compania }).text(item.Nombre_Sucursal).appendTo("#cbocompania");
                })
            },
            error: function (error) {
                console.log(error)
            }
        });

        function abrirModal(json) {

            $("#txtid").val(0);
            $("#cbocompania").val($("#cbocompania option:first").val());
            $("#txtdescripcion").val("");
            $("#cboestado").val(1);

            $("#mensajeError").hide();

            if (json != null) {

                $("#txtid").val(json.Id_Marca_Producto);
                $("#cbocompania").val(json.oId_Compania.Id_Compania);
                $("#txtdescripcion").val(json.Descripcion_Marca);
                $("#cboestado").val(json.Estado_Marca == true ? 1 : 0);
            }

            $("#FormModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            abrirModal(data)

        })

        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var marcaseleccionado = $(this).closest("tr");
            var data = tabladata.row(marcaseleccionado).data();

            swal({
                title: "Esta Seguro?",
                text: "¿Desea eliminar la marca?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {

                    jQuery.ajax({
                        url: '@Url.Action("EliminarMarca", "Productos")',
                        type: "POST",
                        data: JSON.stringify({ Id_Marca_Producto: data.Id_Marca_Producto }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado) {
                                tabladata.row(marcaseleccionado).remove().draw();
                            } else {
                                swal("No se pudo eliminar", data.mensaje, "error")
                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }
                    });
                });
            console.log(data);
        })

        function Guardar() {

            var Marcas = {

                oId_Compania: {
                    Id_Compania: $("#cbocompania option:selected").val(),
                    //Nombre_Sucursal: $("#cbocompania option:selected").text()
                },
                Id_Marca_Producto: $("#txtid").val(),
                Descripcion_Marca: $("#txtdescripcion").val(),
                Estado_Marca: $("#cboestado").val() == 1 ? true : false
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarMarca", "Productos")',
                type: "POST",
                data: JSON.stringify({ obj: Marcas }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
               success: function (data) {

                   $(".modal-body").LoadingOverlay("hide");

                   //NUEVO
                   if (Marcas.Id_Marca_Producto == 0) {

                       if (data.resultado != 0) {
                            Marcas.Id_Marca_Producto = data.resultado
                            tabladata.row.add(Marcas).draw(false);
                            $("#FormModal").modal("hide");

                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                    //MODIFICAR
                    else {

                       if (data.resultado) {
                            tabladata.row(filaSeleccionada).data(Marcas).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
               error: function (error) {

                   $(".modal-body").LoadingOverlay("hide");
                   $("#mensajeError").text("Error Ajax");
                   $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }
            });

        }


    </script>


}

CapaPresentacion/Views/Productos/Sustancias.cshtml
@{
    ViewBag.Title = "Sustancias";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb mb-4 mt-4">
    <li class="breadcrumb-item"><a href="@Url.Action("Index","Home")">Escritorio</a></li>
    <li class="breadcrumb-item active">Sustancias</li>
</ol>

<div class="card">
    <div class="card-header">

        <i class="fas fa-flask me-1"></i> Sustancias
    </div>

    <div class="card-body">
        <div class="row">
            <div class="col-12">
                <button type="button" class="btn btn-success" onclick="abrirModal(null)">Registrar</button>
            </div>
        </div>

        <hr />

        <table id="tabla" class="display cell-border" style="width:100%">
            <thead>
                <tr>
                    <th>Descripcion</th>
                    <th>Estado</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>

    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="FormModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-dark text-white">
                <h5 class="modal-title" id="exampleModalLabel">Sustancia</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body g-2">

                <input id="txtid" type="hidden" value="0" />

                <div class="row g-1">
                    <div class="col-sm-6">
                        <label for="txtdescripcion" class="form-label">Descripcion</label>
                        <input type="text" class="form-control" id="txtdescripcion">
                    </div>
                    <div class="col-sm-6">
                        <label for="cboestado" class="form-label">Estado</label>
                        <select id="cboestado" class="form-select">
                            <option value="1">Activo</option>
                            <option value="0">No activo</option>
                        </select>
                    </div>
                </div>

                <!--Mensaje de alerta-->
                <div class="row mt-2">
                    <div class="col-12">

                        <div id="mensajeError" class="alert alert-danger" role="alert">
                            A simple danger alert—check it out!
                        </div>

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" onclick="Guardar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


@section scripts{
    <script>

        var tabladata;
        var filaSeleccionada;

        tabladata = $("#tabla").DataTable({
            responsive: true,
            ordering: false,
            "ajax": {
                url: '@Url.Action("ListarSustancia", "Productos")',
                type: "GET",
                dataType: "json"
            },
            "columns": [
                { "data": "Descripcion" },
                {
                    "data": "Estado_Sustancia", "render": function (valor) {
                        if (valor) {
                            return '<span class="badge bg-success">Activo</span>'
                        } else {
                            return '<span class="badge bg-danger">No activo</span>'
                        }
                    }
                },
                {
                    "defaultContent": '<button type="button" class="btn btn-primary btn-sm btn-editar"><i class="fas fa-pen"></i></button>' +
                        '<button type="button" class="btn btn-danger btn-sm ms-2 btn-eliminar"><i class="fas fa-trash"></i></button>',
                    "orderable": false,
                    "searchable": false,
                    "width": "90px"
                }
            ],
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.11.3/i18n/es_es.json"
            }

        });

        function abrirModal(json) {

            $("#txtid").val(0);
            $("#txtdescripcion").val("");
            $("#cboestado").val(1);

            $("#mensajeError").hide();

            if (json != null) {

                $("#txtid").val(json.Id_Sustancia);
                $("#txtdescripcion").val(json.Descripcion);
                $("#cboestado").val(json.Estado_Sustancia == true ? 1 : 0);
            }

            $("#FormModal").modal("show");
        }

        $("#tabla tbody").on("click", '.btn-editar', function () {

            filaSeleccionada = $(this).closest("tr");

            var data = tabladata.row(filaSeleccionada).data();

            abrirModal(data)

        })

        $("#tabla tbody").on("click", '.btn-eliminar', function () {

            var sustanciaseleccionado = $(this).closest("tr");
            var data = tabladata.row(sustanciaseleccionado).data();

            swal({
                title: "Esta Seguro?",
                text: "¿Desea eliminar el tipo de cliente?",
                type: "warning",
                showCancelButton: true,
                confirmButtonClass: "btn-primary",
                confirmButtonText: "Si",
                cancelButtonText: "No",
                closeOnConfirm: true
            },
                function () {

                    jQuery.ajax({
                        url: '@Url.Action("EliminarSustancia", "Productos")',
                        type: "POST",
                        data: JSON.stringify({ Id_Sustancia: data.Id_Sustancia }),
                        dataType: "json",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            if (data.resultado) {
                                tabladata.row(sustanciaseleccionado).remove().draw();
                            } else {
                                swal("No se pudo eliminar", data.mensaje, "error")
                            }
                        },
                        error: function (error) {
                            console.log(error)
                        }
                    });
                });
            console.log(data);
        })

        function Guardar() {

            var Sustancias = {

                Id_Tipo_Cliente: $("#txtid").val(),
                Descripcion: $("#txtdescripcion").val(),
                Estado_Tipo_Cliente: $("#cboestado").val() == 1 ? true : false
            }

            jQuery.ajax({
                url: '@Url.Action("GuardarSustancia", "Productos")',
                type: "POST",
                data: JSON.stringify({ obj: Sustancias }),
                dataType: "json",
                contentType: "application/json; charset=utf-8",
               success: function (data) {

                   $(".modal-body").LoadingOverlay("hide");

                   //NUEVO
                   if (Sustancias.Id_Sustancia == 0) {

                       if (data.resultado != 0) {
                           Sustancias.Id_Sustancia = data.resultado
                           tabladata.row.add(Sustancias).draw(false);
                            $("#FormModal").modal("hide");

                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                    //MODIFICAR
                    else {

                       if (data.resultado) {
                            tabladata.row(filaSeleccionada).data(Sustancias).draw(false);
                            filaSeleccionada = null;
                            $("#FormModal").modal("hide");
                        } else {
                            $("#mensajeError").text(data.mensaje);
                            $("#mensajeError").show();
                        }
                    }
                },
               error: function (error) {

                   $(".modal-body").LoadingOverlay("hide");
                   $("#mensajeError").text("Error Ajax");
                   $("#mensajeError").show();
                },
                beforeSend: function () {
                    $(".modal-body").LoadingOverlay("show", {
                        imageResizeFactor: 2,
                        text: "Cargando...",
                        size: 14
                    })
                }
            });

        }


    </script>


}